Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'

  config.ssh.shell = 'sh'
  config.vm.network 'forwarded_port', guest: 80, host: 80
  # for webpacker hot-loading
  config.vm.network 'forwarded_port', guest: 3035, host: 3035
  config.vm.network 'forwarded_port', guest: 3036, host: 3036

  # ホストのsshの鍵を共有
  config.vm.provision 'file', source: '~/.ssh', destination: '/home/vagrant/.ssh'

  config.vm.provider 'virtualbox' do |vm|
    # メモリのサイズは各環境でよしなに設定すること
    vm.memory = 8192
  end

  config.vm.provision 'ansible_local' do |ansible|
    ansible.playbook = 'ansible/site.yml'
  end
end
