# /* vim: set filetype=ruby : */
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.99.100"

  config.ssh.shell = "sh"
  config.disksize.size = '64GB'

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "8192"  # set adequate memory size
    vb.cpus = 2
    vb.customize [
      "modifyvm", :id,
      "--vram", "256",
      "--clipboard", "bidirectional",
      "--draganddrop", "bidirectional",
      "--accelerate3d", "on",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--chipset", "ich9",
      "--pae", "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.provision "file", source: "../ansible", destination: "/home/vagrant/ansible"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/home/vagrant/ansible/site.yml"
    ansible.install_mode = "pip"
  end
end
