  - name: install apt repositories
    apt_repository: repo={{ item }}
    with_items: '{{ apt_repositories }}'
    become: yes

  - name: install apt packages
    apt: name={{ apt_packages }} state=present update_cache=no
    become: yes

  - name: install apt packages from deb
    apt:
      deb: https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
      state: present
      update_cache: no
    become: yes
