Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.99.100"

  config.ssh.shell = "sh"

  config.vm.provision "file", source: "../ansible", destination: "/home/vagrant/ansible"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/home/vagrant/ansible/site.yml"
    ansible.install_mode = "pip"
  end
end