Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.ssh.shell = "sh"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  # for webpacker hot-loading
  config.vm.network "forwarded_port", guest: 3035, host: 3035
  config.vm.network "forwarded_port", guest: 3036, host: 3036

  config.vm.provision "file", source: "../ansible", destination: "/home/vagrant/ansible"

  # ホストのsshの鍵を共有
  config.vm.provision "file", source: "~/.ssh", destination: "/home/vagrant/.ssh"

  config.vm.provider "virtualbox" do |vm|
    # メモリのサイズは各環境でよしなに設定すること
    vm.memory = 8192
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/home/vagrant/ansible/site.yml"
    ansible.install_mode = "pip"
  end
end
