  - name: install apt repositories
    apt_repository: repo={{ item }}
    with_items: '{{ apt_repositories }}'
    become: yes

  - name: install apt packages
    apt: name={{ apt_packages }} state=present update_cache=no
    become: yes
